### ISSUE TITLE
[C++][Parquet] lz4 codec is not compatible with Hadoop Lz4Codec

### ISSUE THREAD

**Issue by rok** [rok/test-parquet-cpp#712]
As described in HADOOP-12990, the Hadoop `Lz4Codec` uses the lz4 block format, and it prepends 8 extra bytes before the compressed data. I believe that lz4 implementation in parquet-cpp also uses the lz4 block format, but it does not prepend these 8 extra bytes.

 

Using Java parquet-mr, I wrote a Parquet file with lz4 compression:
```java

$ parquet-tools meta /tmp/f4a1c7f57cb1c98c2b9da3b25b16d027df5d2f1cf55adb79374c154fbd79011f
file:        file:/tmp/f4a1c7f57cb1c98c2b9da3b25b16d027df5d2f1cf55adb79374c154fbd79011f
creator:     parquet-mr version 1.10.1 (build a89df8f9932b6ef6633d06069e50c9b7970bebd1)file schema:
--------------------------------------------------------------------------------
c1:          REQUIRED INT64 R:0 D:0
c0:          REQUIRED BINARY R:0 D:0
v0:          REQUIRED INT64 R:0 D:0row group 1: RC:5007 TS:28028 OFFSET:4
--------------------------------------------------------------------------------
c1:           INT64 LZ4 DO:0 FPO:4 SZ:24797/25694/1.04 VC:5007 ENC:DELTA_BINARY_PACKED ST:[min: 1566330126476659000, max: 1571211622650188000, num_nulls: 0]
c0:           BINARY LZ4 DO:0 FPO:24801 SZ:279/260/0.93 VC:5007 ENC:PLAIN,RLE_DICTIONARY ST:[min: 0x7471732F62656566616C6F2F746F6D6163636F2D66782D6D6B74646174612D6C69766573747265616D, max: 0x7471732F62656566616C6F2F746F6D6163636F2D66782D6D6B74646174612D6C69766573747265616D, num_nulls: 0]
v0:           INT64 LZ4 DO:0 FPO:25080 SZ:1348/2074/1.54 VC:5007 ENC:PLAIN,RLE_DICTIONARY ST:[min: 0, max: 9, num_nulls: 0] 
```
When I attempted to read this file with parquet-cpp, I got the following error:
```java

>>> import pyarrow.parquet as pq
>>> pq.read_table('/tmp/f4a1c7f57cb1c98c2b9da3b25b16d027df5d2f1cf55adb79374c154fbd79011f')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skim/miniconda3/envs/arrow/lib/python3.8/site-packages/pyarrow/parquet.py", line 1536, in read_table
    return pf.read(columns=columns, use_threads=use_threads,
  File "/home/skim/miniconda3/envs/arrow/lib/python3.8/site-packages/pyarrow/parquet.py", line 1260, in read
    table = piece.read(columns=columns, use_threads=use_threads,
  File "/home/skim/miniconda3/envs/arrow/lib/python3.8/site-packages/pyarrow/parquet.py", line 707, in read
    table = reader.read(**options)
  File "/home/skim/miniconda3/envs/arrow/lib/python3.8/site-packages/pyarrow/parquet.py", line 336, in read
    return self.reader.read_all(column_indices=column_indices,
  File "pyarrow/_parquet.pyx", line 1130, in pyarrow._parquet.ParquetReader.read_all
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
OSError: IOError: Corrupt Lz4 compressed data. 
```
 

<https://github.com/apache/arrow/issues/3491> reported incompatibility in the other direction, using Spark (which uses the Hadoop lz4 codec) to read a parquet file that was written with parquet-cpp.

 

Given that the Hadoop lz4 codec has long been in use, and users have accumulated Parquet files that were written with this implementation, I propose changing parquet-cpp to match the Hadoop implementation.

 

See also:
- https://issues.apache.org/jira/browse/PARQUET-1241?focusedCommentId=16574328#comment-16574328
- https://issues.apache.org/jira/browse/PARQUET-1241?focusedCommentId=16585288#comment-16585288

**Reporter**: [Steve M. Kim](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chairmank)
#### Related issues:
- [[C++][Parquet] Tracking issue for cross-implementation LZ4 Parquet compression compatibility](https://issues.apache.org/jira/browse/ARROW-9177) (is fixed by)
- [[C++] Fix reading LZ4-compressed Parquet files produced by Java Parquet implementation](https://issues.apache.org/jira/browse/ARROW-11301) (is related to)
- [[C++] Disable LZ4 codec](https://issues.apache.org/jira/browse/PARQUET-1515) (is related to)
- [[C++] Use LZ4 frame format](https://issues.apache.org/jira/browse/PARQUET-1241) (is related to)
- [Support LZ4_RAW codec](https://issues.apache.org/jira/browse/PARQUET-2196) (is related to)
#### PRs and other links:
- [GitHub Pull Request #47](https://github.com/apache/arrow-testing/pull/47)
- [GitHub Pull Request #7789](https://github.com/apache/arrow/pull/7789)
- [GitHub Pull Request #13](https://github.com/apache/parquet-testing/pull/13)
- [GitHub Pull Request #14](https://github.com/apache/parquet-testing/pull/14)

<sub>**Note**: *This issue was originally created as [PARQUET-1878](https://issues.apache.org/jira/browse/PARQUET-1878). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by rok** [comment]
[Antoine Pitrou](https://issues.apache.org/jira/browse/PARQUET-1878?#comment-17199917) / @pitrou:
Responding to myself: parquet-mr doesn't use the Hadoop Snappy codec because:
```Java

 * Snappy compression codec for Parquet.  We do not use the default hadoop
 * one since that codec adds a blocking structure around the base snappy compression
 * algorithm.  This is useful for hadoop to minimize the size of compression blocks
 * for their file formats (e.g. SequenceFile) but is undesirable for Parquet since
 * we already have the data page which provides that.
```

but for some reason it didn't bother to do the same for LZ4. Uh oh :-/

**Comment by rok** [comment]
[mario luzi](https://issues.apache.org/jira/browse/PARQUET-1878?#comment-17279210):
@pitrou  would you be so kind to  tell me what it is the right java project for this ? are you sure that problem is there and not anymore here ? looking to this arrow parquet code i found the Codec LZ4_hadoop , so i suppose someone added it and saw it working before put this ticket as resolved.....but i'm not able to read LZ4 file from hadoop .
